### ISSUE TITLE
With multi-select on, There is a problem with the performance of undo

### ISSUE THREAD

**Issue by sunxd-lab** [DHTMLX/gantt#105]
When I batch select and drag many times，then undo. It's not back to where it was last time.

`
gantt.plugins({
    undo: true,
    multiselect:true,
});
`

**Comment by gearcoded** [comment]
@sunxd-lab,
Most likely, the issue occurs because of a bug in Gantt with the multiselect extension. When the extension is added and you select a task, the events fire twice for that task if you do something with it.

But if you make the changes with the Gantt API, the Undo extension can revert the changes correctly.
For example, you can select several tasks in the following sample and use the `Move Forward` and `Move Backward` buttons. After you undo the changes, the dates will be restored correctly:
https://docs.dhtmlx.com/gantt/samples/?sample=%2702_extensions/09_multiselection.html%27&filter=%27multi%27

But if you move tasks manually, they will have different dates after you undo the changes.

The dev team will fix the bug in the future, but I cannot give you any ETA.

**Comment by gearcoded** [comment]
**@sunxd-lab**,
The dev team fixed the bug with the multiselect extension, so now the events don't fire twice for the selected task:
https://docs.dhtmlx.com/gantt/whatsnew.html#x8318x90x8319x:~:text=Fix%20the%20duplicate%20event%20firing%20while%20interacting%20with%20a%20selected%20task%20when%20the%20Multiselect%20extension%20is%20enabled

You can see that the bug is no longer reproduced in the following samples:
http://snippet.dhtmlx.com/5/4c9b1a86e
https://snippet.dhtmlx.com/5/eb6369144
https://snippet.dhtmlx.com/5/b7925f34e
