### ISSUE TITLE
Lightbox setting "wide_form" not working properly

### ISSUE THREAD

**Issue by wiemax1093** [DHTMLX/gantt#116]
Hello, 
I am just trying out this solution and found out that when trying to get the lightbox from not in wide_form it does not "render" as intended/ work as soon as you have the section "time" - it seems this bug was reported around 2 years ago already as a comment under the documentation section of it.
 Anything that can be done here?

**Comment by gearcoded** [comment]
**@wiemax1093**,
As mentioned in the [comment](https://docs.dhtmlx.com/gantt/api__gantt_wide_form_config.html#comment-6475270602) below the article, it is a bug in Gantt. But there is a workaround for that: you can set any name for the `time` section except the `time` name, then the `wide_form` config won't be enabled if you didn't do that.
Here is the snippet:
https://snippet.dhtmlx.com/c3e8g6rv

**Comment by gearcoded** [comment]
**@wiemax1093**,
The dev team fixed the bug when Gantt switched to the wide form for the lightbox:
https://docs.dhtmlx.com/gantt/whatsnew.html#x8318x90x8319x:~:text=Prevent%20the%20lightbox%20from%20switching%20to%20the%20wide_form%20mode%20upon%20adding%20the%20Time%20section

You can see that the bug is no longer reproduced in the following samples:
https://snippet.dhtmlx.com/5/e9c167d2f
https://snippet.dhtmlx.com/siaqtahv
