### ISSUE TITLE
Gantt is undefined 

### ISSUE THREAD

**Issue by ATestEnG** [DHTMLX/gantt#124]
version  "dhtmlx-gantt": "8.0.6",
import {gantt,Gantt} from "dhtmlx-gantt";
![image](https://github.com/user-attachments/assets/e0d211d3-f1eb-49c1-ba62-eca578c61055)
i try many time, it is aways undefined
little "g" is an Object   but  capital 'G' is undefined
![image](https://github.com/user-attachments/assets/96944102-4ee3-42fb-be50-dd2ffef89d48)

**Comment by ATestEnG** [comment]
by the way  construct  is  vue3 + ts + vite

**Comment by gearcoded** [comment]
**@ATestEnG**, it seems that you try to use the GPL version. It doesn't have the feature of creating a new Gantt instance, so the `Gantt` object is not available. This feature is available in the Pro versions (Commercial, Enterprise, Ultimate licenses):
https://docs.dhtmlx.com/gantt/desktop__multiple_gantts.html

So, you need to purchase the license and install the Pro version to get this feature.
Or you can continue using the GPL version, but you need to manually reset everything when you switch to another page/tab/view instead of using the `destructor` method.
The following article explains what should be done:
https://docs.dhtmlx.com/gantt/desktop__gantt_instance.html

Here is the demo:
https://files.dhtmlx.com/30d/c0a7cdde5ff4139e785733d9bfdbc9fb/vue3+gantt-gpl.zip
