### ISSUE TITLE
onAfterTaskMove called many times when dragging a task

### ISSUE THREAD

**Issue by tylerjwatson** [DHTMLX/gantt#13]
Hi guys,

I have a dhtmlx gantt control in use in an AngularJS directive (using the slightly modified ajs samples) with data that contains the following prototype:

```json
{
  "data": [
    {
      "id": 840,
      "duration": 1,
      "open": true,
      "parent": 0,
      "progress": 0,
      "start_date": "23-02-2017",
      "text": "1. Acquire Bagel2"
    },
    {
      "id": 841,
      "duration": 1,
      "open": true,
      "parent": 839,
      "progress": 0,
      "start_date": "28-02-2017",
      "text": "3. Become the bagel"
    },
    {
      "id": 839,
      "duration": 1,
      "open": true,
      "parent": 840,
      "progress": 0,
      "start_date": "25-02-2017",
      "text": "2. Consume Bagel"
    }
  ],
  "links": [
    {
      "id": 118,
      "source": 840,
      "target": 839,
      "type": 0
    },
    {
      "id": 119,
      "source": 839,
      "target": 841,
      "type": 0
    }
  ]
}
```

This gantt instance has `order_branch` turned on, and this particular gantt has the `onAfterTaskMove` event attached, pointing to a simple `console.log`.  The event can be called up to a hundred times for a simple move, without letting the mouse button go.  Attached is a simple picture of the handler for `onAfterTaskMove`.

![image](https://cloud.githubusercontent.com/assets/5001408/23351149/1f267c66-fd0b-11e6-9af0-20c9b0aedb4a.png)

Is this expected behavior, or have I stumbled across something sinister?

Cheers,
T.

**Comment by AlexKlimenkov** [comment]
Hi,
this is expected behavior. Internally, drag and drop uses gantt.moveTask method to place task in correct position under the cursor. It can happen many times during dnd and each call of .moveTask fires onBeforeTaskMove and onAfterTaskMove
https://docs.dhtmlx.com/gantt/api__gantt_movetask.html
Try checking onRowDragEnd if you need to trace the end of drag and drop 
https://docs.dhtmlx.com/gantt/api__gantt_onrowdragend_event.html

**Comment by tylerjwatson** [comment]
Awesome, thank you for your feedback. :)
