### ISSUE TITLE
in the version 4.1, when set gantt.config.show_chart = false there has some issue?

### ISSUE THREAD

**Issue by suweien** [DHTMLX/gantt#17]
I am using dhtmlxGantt v.4.1.0 Stardard

When add this config
gantt.config.show_chart = false

here has some issue like 
Uncaught TypeError: Cannot read property 'length' of undefined.
Any fix for this ?

**Comment by AlexKlimenkov** [comment]
Hi,
we confirmed regression,
as a workaround, you can disable smart_scales config:
`gantt.config.smart_scales = false;`

also, we're going to publish a bugfix release (v4.1.19) which fixes this issue. Unfortunately, this repository will be updated on next major release only, so in order to get the bugfix you'll either need a commercial version of component, or to use a workaround with smart_scales, or do a temporary fix right in the source codes - find gantt._refreshScales method and add checking for 'show_chart' config like here https://www.screencast.com/t/JETfJxhsY5

**Comment by AlexKlimenkov** [comment]
The fix has was published in v4.1.19 and will be included in the next minor/major update that will be published here
https://dhtmlx.com/blog/gantt-scheduler-maintenance-release/
