### ISSUE TITLE
Ability to Import as a Module

### ISSUE THREAD

**Issue by mpalmr** [DHTMLX/gantt#18]
I see there's an [npm module](https://www.npmjs.com/package/dhtmlx-gantt) published, and when installing it to my project I attempted to import it via Webpack with `import gantt from 'dhtmlx-gantt';`. After this didn't work I took a look at the source code and saw that nothing's being exported as a module.

Since this is an npm module after all, wouldn't it make sense to make this a module to be used by module bundlers / loaders?

**Comment by gewisser** [comment]
Also interested is this question

**Comment by robv8r** [comment]
The best I could do is use bower.  @plazarev and @Stanislav-Wolski are there any plans to migrate the JavaScript to either CJS, AMD, or ES6 so that we can use it in places other than a browser?

**Comment by robv8r** [comment]
One option would be to port the Gantt to TypeScript and have it produce any module you like.  My preference would be UMD since it covers nearly all use cases.

**Comment by ranebo** [comment]
Try `import 'dhtmlx-gantt';`
Then the `gantt` variable is accessible.
You will also need to import the css file either by the cdn or importing from the node_modules directory into your style sheet:
`@import "../node_modules/dhtmlx-gantt/codebase/dhtmlxgantt.css"`

**Comment by AlexKlimenkov** [comment]
Hi,
currently, there are no plans to publish CJS/ES6/AMD compatible builds. Not in the sense that it was rejected, but we didn't do any research so far due to a very little demand. We have type definitions for TS https://www.npmjs.com/package/@types/dhtmlxgantt , so everything should be pretty usable with the TypeScript. The type definitions are a bit behind the latest version of gantt though, we'll update them soon.
Probably, we could wrap gantt declaration into UMD and keep current global declaration in order to break any compatibility, if it makes sense. 

Regarding using dhtmlxgantt outside a browser - it's unlikely to happen soon, since again, we haven't researched it, and from the first look it may require quite a bit of change all around the codebase. Can you give me a use-case when you'll want to run gantt outside the browser?

I've added both items (CJS/AMD/UMD and running outside a browser) to the tracker to investigate later.

Closing the issue for now. Feel free to reopen the issue if you have any comments.

**Comment by sergids** [comment]
Feature already added in the last release
