### ISSUE TITLE
Disable auto save

### ISSUE THREAD

**Issue by eduardobelchior** [DHTMLX/gantt#24]
How to disable auto save activities and save only after button click?

**Comment by AlexKlimenkov** [comment]
Hi,
autosaving is done by the dataProcessor module - https://docs.dhtmlx.com/gantt/desktop__server_side.html#technique
https://docs.dhtmlx.com/dataprocessor__index.html
In order to disable autosaving you can either not use the dataProcessor at all, or disable auto-submit using this .setUpdateMode method:
https://docs.dhtmlx.com/api__dataprocessor_setupdatemode.html
`dataprocessor.setUpdateMode("off");`
after that you'll be able to send changed using this method  https://docs.dhtmlx.com/api__dataprocessor_senddata.html
