### ISSUE TITLE
Strange behavior of template.date_scale

### ISSUE THREAD

**Issue by Prancing-Pony** [DHTMLX/gantt#27]
I've reproduced it here: http://jsfiddle.net/fmnabkac/

When I first render the component the template is functional and 'icecream' appears instead of 'Apr' for the top scale.

When I click for the first time and modify the scales I get 'Apr' instead of 'icecream', yet I set the template.date_scale before, (and after, for good measure).

When I click again I get 'icecream' and it will stay 'icecream'. This doesn't match the behaviour of the first event.  Am I missing something?

**Comment by AlexKlimenkov** [comment]
Hi,
it's a bit confusing behavior, but I'm not sure there's an actual error. date_scale config and template are not expected to be used together, it's assumed the devs would be using either of them - a declarative config for simple templates or a template function for something that can't be expressed via config string. 

1) the date_scale template function is generated from the config when you initialize gantt, if was not defined prior to that:
gantt.templates.date_scale = gantt.date.date_to_str(gantt.config.date_scale);

2) onTemplatesReady event is fired when all default templates are initialized by gantt during gantt.init. In your code, you redefine date_scale template there and thats the reason why 'icecream' template is used when gantt is displayed for the first time.

3) Then, if the date_scale config string changes, gantt updates the template function from config string  - this is what happens when you redefine a config and a template from 'click' event and rewrites your custom template. onTemplatesReady doesn't fire in that case because it fires only during gantt.init.

4) On the second click the date_scale  config value doesn't actually changes, so gantt won't reset the template which you assign. thus, the 'icecream' template is applied again


I'd suggest using either date_scale config or a template and not both, this should remove any uncertain behavior.


Btw, regarding something in the jsfiddle code, please note gantt.attachEvent inside the click handler: 

```
document.addEventListener("click", (evnt) => {
...
	gantt.attachEvent("onTemplatesReady", () => {
		// Looks like scale_cell_class only works on the top scale
		// gantt.templates.scale_cell_class = OnlyWorkHours;
		gantt.templates.date_scale = function(date) {
		      return "icecream";
		};
	});
});
```

gantt.attachEvent does not replace the previous event, a new handler will be added each time. Which means that after several clicks more and more handlers start fire on onTemplatesReady. 
For an example pls check this jsfiddle http://jsfiddle.net/nrz61d90/2/ - try clicking on gantt couple of times.

And from the code comments:

>  Looks like scale_cell_class only works on the top scale


Yes, that is correct. But you can apply scale_cell_class to all scales by switching this config https://docs.dhtmlx.com/gantt/api__gantt_inherit_scale_class_config.html
Alternatively, you can define for each scale using `css` property https://docs.dhtmlx.com/gantt/desktop__second_scale.html#settingthescalesstyle

**Comment by Prancing-Pony** [comment]
Now I understand, thanks for the quick response!
