### ISSUE TITLE
Gantt chart not rendering tasks on Chrome.

### ISSUE THREAD

**Issue by riosr8** [DHTMLX/gantt#36]
Hello,

We have a React application that uses the gantt chart, and recently encountered an issue with the gantt chart not showing tasks when using Google Chrome. The tasks themselves do get rendered to the DOM though, and the only way they seem to appear again is if we go to the inspector and disable any of the css properties. 

Although, Firefox and Safari work perfectly fine.

**Comment by AlexKlimenkov** [comment]
Hi,
can you share some kind of demo where this issue can be reproduced?
I don't think I've encountered such problem before.
One related thing is the sizing approach of gantt container - we use `style="height:100%;` for gantt container in most of our examples, [like here](https://github.com/DHTMLX/gantt-howto-node/blob/master/public/index.html#L19). When this element is copied elsewhere, where outer container doesn't have an initial size specified, gantt collapses to the minimal height (i.e. "100% from zero"). And it can be fixed by changing container height to some other value, e.g. `800px` or `100vh`. 
Other than that, I don't think I know what might have happened
