### ISSUE TITLE
How to to show tooltip for the linkage links in 4.1.19 version 

### ISSUE THREAD

**Issue by vittal288** [DHTMLX/gantt#44]
I have a working example with 6.*.* versions
https://snippet.dhtmlx.com/05f48085c

**Comment by pkustova** [comment]
Hello @vittal288 ,

As you know, the ability to create tooltip for links (and all other elements) was implemented only in Feb this year. https://docs.dhtmlx.com/gantt/whatsnew.html#61

4.1 was released more than 3 years ago: https://docs.dhtmlx.com/gantt/whatsnew.html#41

Too many changes have been made since then, so, unfortunately, there is no easy way to solve your issue. I advise you to update your version of DHTMLX Gantt. In addition to tooltips for links, you will get many other features that were developed during 3 years.
