### ISSUE TITLE
Timeline rendering problem

### ISSUE THREAD

**Issue by lishenhello** [DHTMLX/gantt#66]
Hello, In the process of sliding left and right, when the actual time interval is much larger than the plan interval, the actual time is not rendered when the plan timeline stops rendering.Thanks

**Comment by gearcoded** [comment]
@lishenhello, let's clarify the terms. By the actual time interval you mean the displayed date range, and by the plan interval you mean the task dates. Is that correct? 
If it is, I couldn't reproduce the issue in the following snippet:
http://snippet.dhtmlx.com/5/e611d0a46
If that is the case, please, add your configuration to the snippet above and make sure that the issue is reproduced there. Then, click on the `Share` button and send me the link.
Or send me a ready demo with all the necessary Javascript and CSS files so that I can reproduce the issue locally.


If you mean something different, please, describe your question in more detail.

**Comment by lishenhello** [comment]
@gearcoded I know the reason. After the task is split, because the duration of my parent task is the duration of the acquired planned task, and the duration of the actual task is much longer than that of the planned task, this will happen. Thank you again
