### ISSUE TITLE
drag task, other function was fired.

### ISSUE THREAD

**Issue by Hsensor** [DHTMLX/gantt#87]
![image](https://user-images.githubusercontent.com/8132535/206137476-33e88751-c3b7-4ccf-8f48-4e596eb4ed84.png)
![image](https://user-images.githubusercontent.com/8132535/206137655-531362e4-7d90-43d8-91d5-5b40cd8f91d2.png)

**Comment by gearcoded** [comment]
This is expected behavior. When you drag a task in the timeline, Gantt repaints the whole row. Task #4 is a project task. Its dates depend on its children. So when you move Task #4.3 to an earlier date, the `start_date` of Task #4 is also changed, and Gantt repaints the whole task row of Task #4.
It will work the same way for other templates.

If you drag tasks #4.1 and #4.2 within the dates of Task #4, the dates of their parent won't be changed, so Gantt won't repaint it, and the templates won't be called.
